apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault-demo

resources:
  - serviceaccounts.yaml
  - vault-token-reviewer-secret.yaml
  - vault-auth-delegator-binding.yaml
  - resources.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: k8s-vault-demo
