apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-vso-auth
  labels:
    app.kubernetes.io/name: todo-vso-auth
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-reviewer
  labels:
    app.kubernetes.io/name: vault-auth-reviewer
automountServiceAccountToken: true
