apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault-demo

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - app-config.yaml
  - backend.yaml
  - frontend.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
